Repository tracked-tools/tracked-built-ins, pull requests merged in 2022-05, with the labels that each got.

#307 Use Ember v4 types
  .github/workflows/CI.yml
  package.json
  tests/unit/object-test.ts
  yarn.lock
Labels: enhancement

#313 Introduce TS support policy with TS 4.4–4.6
  .github/workflows/CI.yml
  README.md
Labels: enhancement

#314 Add type tests and fix a types bug they exposed
  addon/-private/object.d.ts
  package.json
  tests/unit/array-test.ts
  tests/unit/decorator-test.ts
  tests/unit/object-test.ts
  yarn.lock
Labels: bug, enhancement

#321 Directly integrate tracked maps and sets
  addon/-private/decorator.ts
  addon/-private/map.ts
  addon/-private/set.ts
  addon/index.ts
  package.json
  tests/helpers/collection-reactivity.d.ts
  tests/helpers/reactivity.js
  tests/unit/map-test.ts
  tests/unit/set-test.ts
  tests/unit/weak-map-test.ts
  tests/unit/weak-set-test.ts
  types/tracked-maps-and-sets/-private/util.d.ts
  yarn.lock
Labels: internal

#323 chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.15.0 to 5.23.0
  addon/-private/object.js
  package.json
  tests/helpers/collection-reactivity.js
  tests/helpers/reactivity.js
  yarn.lock
Labels: dependencies

#330 Drop support for Node 12
  .github/workflows/CI.yml
  README.md
  package.json
Labels: breaking

#331 Ignore generated types in repo
  .gitignore
  index.d.ts
Labels: internal

#30 Trigger update after calling `delete` on an item
  addon/-private/object.js
  tests/unit/object-test.ts
Labels: enhancement

#336 Switch to using `@tsconfig/ember`
  addon/package.json
  addon/tsconfig.json
  test-app/package.json
  test-app/tests/unit/object-test.ts
  test-app/tsconfig.json
  yarn.lock
Labels: internal
