Repository tracked-tools/tracked-built-ins, pull requests merged in 2023-09, with the labels that each got.

#408 Move Array#fill to "write then read" methods so the template correctly updates
  addon/src/-private/array.ts
  test-app/tests/unit/array-test.ts
Labels: enhancement

#410 Update compatibility section in README.md
  README.md
Labels: documentation

#412 add .npmrc
  .npmrc
  pnpm-lock.yaml
Labels: dependencies
