Repository tracked-tools/tracked-built-ins, pull requests merged in 2024-12, with the labels that each got.

#431 Add push-dist workflow so folks can point at unreleased GH code if they wish
  .github/workflows/push-dist.yml
Labels: internal

#432 Update CI status badge
  README.md
Labels: documentation

#434 Drop support for TypeScript < 5.5
  .github/workflows/CI.yml
  README.md
  addon/package.json
  package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: breaking
